### ISSUE TITLE
Undeclared variable x__len1 when working with a two-dimensional array

### ISSUE THREAD

**Issue by Oleg-N-Cher** [jtempl/ofront#37]
```
MODULE Test;

TYPE
T1 = ARRAY 5 OF REAL;
T2 = ARRAY 5 OF T1;

PROCEDURE Do4 ( x: ARRAY OF ARRAY OF REAL );
END Do4;

PROCEDURE Do3 ( x: ARRAY OF T1 );
BEGIN
  Do4( x );
END Do3;

END Test.
```

It translates successfully, but the resulting C-file are no longer compiled.

```
/* Ofront 1.4 -xtpkamG */
#include "SYSTEM.h"

typedef
	REAL Test_T1[5];

typedef
	Test_T1 Test_T2[5];




static void Test_Do3 (Test_T1 *x, LONGINT x__len);
static void Test_Do4 (REAL *x, LONGINT x__len, LONGINT x__len1);


static void Test_Do4 (REAL *x, LONGINT x__len, LONGINT x__len1)
{
	__DUP(x, x__len * x__len1, REAL);
	__DEL(x);
}

static void Test_Do3 (Test_T1 *x, LONGINT x__len)
{
	__DUP(x, x__len, Test_T1);
	Test_Do4(x, x__len, x__len1);
	__DEL(x);
}


int main(int argc, char **argv)
{
	__INIT(argc, argv);
	__REGMAIN(Test, 0);
/* BEGIN */
	__FINI;
} 
```

The calling of procedure Do4 from procedure Do3:

`Test_Do4(x, x__len, x__len1);`

There is an undeclared variable x__len1.

Thanks to **GameHunter** for information about this bug.

**Comment by Oleg-N-Cher** [comment]
I suggest such a fix:

• https://github.com/Oleg-N-Cher/OfrontPlus/issues/73

**Comment by jtempl** [comment]
Thanks for the report.
I will look at [https://github.com/Oleg-N-Cher/OfrontPlus/commit/b819c88c11e2ad6ee1327c8443f4273ee6595dfc](url) shortly.

**Comment by jtempl** [comment]
There is a related bug in OfrontOPV.Len for POINTER TO ARRAY OF T1.

**Comment by jtempl** [comment]
fixed as proposed by Oleg plus a similar fix in OfronOPV.Len

**Comment by Oleg-N-Cher** [comment]
Thank you for fixing another bug in OPV, Josef.

There's still a problem with the warning of C compiler on this module:

```
MODULE Test;

TYPE
  T1 = ARRAY 5 OF REAL;
  T2 = ARRAY 5 OF T1;

PROCEDURE Do4 ( x: ARRAY OF ARRAY OF REAL );
END Do4;

PROCEDURE Do3 ( x: ARRAY OF T1 );
BEGIN
  Do4( x );
END Do3;

END Test.
```

![image](https://user-images.githubusercontent.com/1090608/68066160-0a0d0000-fd3c-11e9-879f-dd25134b28f6.png)

The reason of warning: casting to (void*) is missing on the arrays in some cases. This issue must solve the problem: https://github.com/Oleg-N-Cher/OfrontPlus/commit/dfd8a3bd9db855b0ae756df92f5db39fd7272b0e

**Comment by Oleg-N-Cher** [comment]
Josef, please also look at:

• https://github.com/Oleg-N-Cher/OfrontPlus/issues/74

It's the serious similar bug, I think.
